school/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.show, name='show'),
    path('<int:id>/', views.content, name='content'),
    path('?q', views.search, name='search'),
    path('addstudent/', views.addstudent, name='addstudent'),
    path('?name', views.adddstu, name='addstu'),
    path('addcourse/', views.course, name='course'),
    path('?course', views.addcourse, name='addcourse'),
    path('students/', views.students, name='students'),
    path('students/delete/<int:id>/', views.deleteStudent, name='delete'),
]

school3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', include('school.urls')),
]

school/models.py
from django.db import models


class Student(models.Model):
    name = models.CharField(max_length=500)
    ac_year = models.CharField(max_length=50)

    def __str__(self):
        return self.name + ' ' + self.ac_year


class Course(models.Model):
    name = name = models.CharField(max_length=250)
    max_degree = models.IntegerField()

    def __str__(self):
        return self.name


class Grade(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, default='')
    degree = models.IntegerField()

    def __str__(self):
        return str(self.degree)

school/views.py
from django.shortcuts import render
from .models import Student, Grade, Course
from django.http import HttpResponse


def show(request):
    all_students = Student.objects.all()
    context = {'all_students': all_students}
    return render(request, 'school/show.html', context)


def content(request, id):
    student = Student.objects.get(pk=id)
    return render(request, 'school/content.html', {'student': student})


def search(request):
    if 'q' in request.GET:
        message = request.GET['q']
        all_students = Student.objects.filter(name__contains=message)
        context = {'all_students': all_students}
        return render(request, 'school/show.html', context)
    else:
        message = 'You submitted an empty form.'
    return HttpResponse(message)


def addstudent(request):
    all_students = Student.objects.all()
    context = {'all_students': all_students}
    return render(request, 'school/addStudent.html', context)


def adddstu(request):
    if 'name' in request.GET:
        message = request.GET['name']
        message2 = request.GET['acyear']
        student = Student()
        student.name = message
        student.ac_year = message2
        student.save()
        grade1 = Grade()
        grade1.student = student
        grade1.course = Course.objects.get(pk=2)
        grade1.degree = int(request.GET['degree'])
        grade1.save()
        return content(request, student.pk)
    else:
        message = 'You submitted an empty form.'
        return HttpResponse(message)


def course(request):
    all_students = Student.objects.all()
    context = {'all_students': all_students}
    return render(request, 'school/addCourse.html', context)


def addcourse(request):
    if 'course' in request.GET:
        message = request.GET['course']
        message2 = int(request.GET['max'])
        course1 = Course()
        course1.name = message
        course1.max_degree = message2
        course1.save()
        return show(request)
    else:
        message = 'You submitted an empty form.'
    return HttpResponse(message)


def students(request):
    all_students = Student.objects.all()
    context = {'all_students': all_students}
    return render(request, 'school/Students.html', context)


def deleteStudent(request, id):
    student = Student.objects.get(pk=id)
    student.delete()
    all_students = Student.objects.all()
    context = {'all_students': all_students}
    return render(request, 'school/show.html', context)

school/templates/school/Students.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>School</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'show' %}" >School</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'show' %}">Home</a></li>
        <li><a href="{% url 'students' %}">Students</a></li>
        <li>
            <a href="{% url 'addstudent' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Student
            </a>
        </li>
        <li>
            <a href="{% url 'course' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Course
            </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">

    </div>
    <div class="col-sm-8 text-left">
      <h1>School's Students</h1>
       <ul>
    {% for stu in all_students %}
       <li><a href="{% url 'content' stu.id %}" >{{ stu.name }}</a></li>
        <form method="get" action="{% url 'delete' stu.id %}">
            <input type="hidden" name="name" value="{{ stu.id }}" >
            <button type="submit" class="btn btn-default">Delete</button>
        </form>
    {% endfor %}
        </ul>

    </div>
    <div class="col-sm-2 sidenav">

    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>School G09</p>
</footer>

</body>
</html>

school/templates/school/addCourse.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'show' %}" >School</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'show' %}">Home</a></li>
        <li><a href="{% url 'students' %}">Students</a></li>
        <li>
            <a href="{% url 'addstudent' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Student
            </a>
        </li>
        <li>
            <a href="{% url 'course' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Course
            </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
    </div>
    <div class="col-sm-8 text-left">
      <form action="{% url 'addcourse' %}" method="get" role="form">

          <div class="form-group">
            <label for="formGroupExampleInput">Course Name</label>
            <input type="text" class="form-control" name="course" value="">
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput2">Max Degree</label>
            <input type="text" class="form-control" name="max" value="">
          </div>
                  <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div>
    <div class="col-sm-2 sidenav">
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>School G09</p>
</footer>

</body>
</html>

school/templates/school/addStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Add Students</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'show' %}" >School</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'show' %}">Home</a></li>
        <li><a href="{% url 'students' %}">Students</a></li>
        <li>
            <a href="{% url 'addstudent' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Student
            </a>
        </li>
        <li>
            <a href="{% url 'course' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Course
            </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
    </div>
    <div class="col-sm-8 text-left">
      <form action="{% url 'addstu' %}" method="get" role="form">

          <div class="form-group">
            <label for="formGroupExampleInput">Student Name</label>
            <input type="text" class="form-control" name="name" value="">
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput2">Academic Year</label>
            <input type="text" class="form-control" name="acyear" value="">
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput">Programming Degree</label>
            <input type="text" class="form-control" name="degree" value="">
          </div>
                  <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div>
    <div class="col-sm-2 sidenav">
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>School G09</p>
</footer>

</body>
</html>

school/templates/school/content.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Student Info</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
      table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    }

    td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
    }

    tr:nth-child(even) {
    background-color: #dddddd;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'show' %}" >School</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'show' %}">Home</a></li>
        <li><a href="{% url 'students' %}">Students</a></li>
        <li>
            <a href="{% url 'addstudent' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Student
            </a>
        </li>
        <li>
            <a href="{% url 'course' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Course
            </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
    </div>
    <div class="col-sm-8 text-left"> 
     <h1>Student Grades</h1>
     <h2>{{ student.name }}</h2>
     <table>
        <tr>
            <th>Course</th>
            <th>Degree</th>
        </tr>
     {% for foo in student.grade_set.all %}

       <tr>
           <td>{{ foo.course }}</td>
           <td>{{ foo.degree }}</td>
       </tr>
     {% endfor %}

        </table>
    </div>
    <div class="col-sm-2 sidenav">
    </div>
  </div>
</div>
<footer class="container-fluid text-center">
  <p>School G09</p>
</footer>

</body>
</html>

school/templates/school/show.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>School</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'show' %}" >School</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'show' %}">Home</a></li>
        <li><a href="{% url 'students' %}">Students</a></li>
        <li>
            <a href="{% url 'addstudent' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Student
            </a>
        </li>
        <li>
            <a href="{% url 'course' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Course
            </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
    </div>
    <div class="col-sm-8 text-left">
      <h1>School's Students</h1>
      <form role="search" method="get" action="{% url 'search' %}">
          <div class="form-group">
              <input type="text" class="form-control" name="q" value="">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
          {% for stu in all_students %}
       <li><a href="{% url 'content' stu.id %}" >{{ stu.name }}</a></li>
        </form>
    {% endfor %}
      </form>

    </div>
    <div class="col-sm-2 sidenav">

    </div>
  </div>
</div>
<footer class="container-fluid text-center">
  <p>School G09</p>
</footer>

</body>
</html>